#!/bin/bash

###############################################################################
# Post Summary to GitHub
#
# Posts ONE comprehensive summary when work is complete
#
# Usage (option 1 - Interactive):
#   ./.claude/hooks/post-summary.sh
#
# Usage (option 2 - With arguments):
#   ./.claude/hooks/post-summary.sh \
#     "Your prompt: Add JSDoc comments" \
#     "Achievement: Added docs to 9 files, 460+ lines, all tests passing"
###############################################################################

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Get branch info
BRANCH=$(git branch --show-current 2>/dev/null || echo "")
ISSUE_NUM=$(echo "$BRANCH" | grep -oP '(?:feature|fix|issue|refactor|chore)/(\d+)' | grep -oP '\d+' || echo "")
PR_NUM=$(gh pr list --head "$BRANCH" --json number --jq '.[0].number' 2>/dev/null || echo "")

if [ -z "$ISSUE_NUM" ] && [ -z "$PR_NUM" ]; then
  echo "❌ No issue or PR found"
  exit 1
fi

# Get user input
if [ -n "$1" ]; then
  USER_PROMPT="$1"
  ACHIEVEMENT="$2"
else
  echo "What did you ask Claude to do?"
  read -r USER_PROMPT
  echo "What was achieved?"
  read -r ACHIEVEMENT
fi

# Get commits and files
BASE_BRANCH="main"
COMMITS=$(git log --oneline ${BASE_BRANCH}..HEAD 2>/dev/null | head -10)
COMMIT_COUNT=$(echo "$COMMITS" | wc -l)
CHANGED_FILES=$(git diff --name-only ${BASE_BRANCH}...HEAD 2>/dev/null)
FILE_COUNT=$(echo "$CHANGED_FILES" | grep -v '^$' | wc -l)

# Timing
FIRST_COMMIT=$(git log ${BASE_BRANCH}..HEAD --reverse --format=%ct 2>/dev/null | head -1)
LAST_COMMIT=$(git log -1 --format=%ct)
if [ -n "$FIRST_COMMIT" ]; then
  DURATION=$(( (LAST_COMMIT - FIRST_COMMIT) / 60 ))
  DURATION_STR="${DURATION}m"
else
  DURATION_STR="30m"
fi

TIMESTAMP=$(date '+%Y-%m-%d %H:%M')

# Session number
SESSION_FILE="$SCRIPT_DIR/../session-counter.json"
[ ! -f "$SESSION_FILE" ] && echo '{}' > "$SESSION_FILE"
SESSION_KEY="issue-${ISSUE_NUM}"
SESSION_NUM=$(jq -r ".[\"$SESSION_KEY\"] // 0" "$SESSION_FILE")
SESSION_NUM=$((SESSION_NUM + 1))
jq ".[\"$SESSION_KEY\"] = $SESSION_NUM" "$SESSION_FILE" > "$SESSION_FILE.tmp" && mv "$SESSION_FILE.tmp" "$SESSION_FILE"

# Build comment
COMMENT="## 🔄 Iteration ${SESSION_NUM}

**Time:** ${TIMESTAMP} (~${DURATION_STR})

### 📝 Request
\`\`\`
${USER_PROMPT}
\`\`\`

### ✅ What Was Added

${ACHIEVEMENT}

### 📁 Files Changed (${FILE_COUNT} files)
"

# Add files
echo "$CHANGED_FILES" | head -15 | while read -r file; do
  [ -n "$file" ] && COMMENT="${COMMENT}- \`${file}\`
"
done

[ $FILE_COUNT -gt 15 ] && COMMENT="${COMMENT}
... and $((FILE_COUNT - 15)) more files
"

COMMENT="${COMMENT}

### 📊 Summary

- **Files changed:** ${FILE_COUNT}
- **Commits:** ${COMMIT_COUNT}
- **Duration:** ~${DURATION_STR}

**Commits:**
\`\`\`
${COMMITS}
\`\`\`

---
*Iteration ${SESSION_NUM} • Generated by Claude Code*
"

# Post
if [ -n "$ISSUE_NUM" ]; then
  echo "$COMMENT" | gh issue comment "$ISSUE_NUM" --body-file - && \
    echo "✓ Posted to Issue #${ISSUE_NUM}"
fi

if [ -n "$PR_NUM" ]; then
  echo "$COMMENT" | gh pr comment "$PR_NUM" --body-file - && \
    echo "✓ Posted to PR #${PR_NUM}"
fi

echo "✅ Done!"
