# GitHub Claude Configuration
# Enable auto-responses for architecture discussions only

# Enable auto-responses to @claude mentions
auto_respond: true

# Allow automatic responses for design discussions
manual_only: false

# IMPORTANT: GitHub @claude should provide SUGGESTIONS ONLY
# - Respond with architecture recommendations
# - Discuss design decisions and trade-offs
# - Provide technical guidance
# - DO NOT implement code directly
# - DO NOT push commits
#
# Code implementation is done via Claude Code CLI workflow
